# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.proto.KVService_pb2 as KVService__pb2


class KVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitedVersion = channel.unary_unary(
                '/src.proto.KVService/CommitedVersion',
                request_serializer=KVService__pb2.CommitedVersionReq.SerializeToString,
                response_deserializer=KVService__pb2.CommitedVersionResp.FromString,
                )
        self.PaxosPhase1 = channel.unary_unary(
                '/src.proto.KVService/PaxosPhase1',
                request_serializer=KVService__pb2.PaxosPhase1Req.SerializeToString,
                response_deserializer=KVService__pb2.PaxosPhase1Resp.FromString,
                )
        self.PaxosPhase2 = channel.unary_unary(
                '/src.proto.KVService/PaxosPhase2',
                request_serializer=KVService__pb2.PaxosPhase2Req.SerializeToString,
                response_deserializer=KVService__pb2.PaxosPhase2Resp.FromString,
                )
        self.CommitKey = channel.unary_unary(
                '/src.proto.KVService/CommitKey',
                request_serializer=KVService__pb2.CommitReq.SerializeToString,
                response_deserializer=KVService__pb2.CommitResp.FromString,
                )
        self.GetValue = channel.unary_unary(
                '/src.proto.KVService/GetValue',
                request_serializer=KVService__pb2.GetValueReq.SerializeToString,
                response_deserializer=KVService__pb2.GetValueResp.FromString,
                )
        self.GetItems = channel.unary_unary(
                '/src.proto.KVService/GetItems',
                request_serializer=KVService__pb2.GetItemsReq.SerializeToString,
                response_deserializer=KVService__pb2.GetItemsResp.FromString,
                )


class KVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommitedVersion(self, request, context):
        """Set
        查询指定Key在Service上已Commit的最高Version
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaxosPhase1(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PaxosPhase2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValue(self, request, context):
        """Get
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitedVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitedVersion,
                    request_deserializer=KVService__pb2.CommitedVersionReq.FromString,
                    response_serializer=KVService__pb2.CommitedVersionResp.SerializeToString,
            ),
            'PaxosPhase1': grpc.unary_unary_rpc_method_handler(
                    servicer.PaxosPhase1,
                    request_deserializer=KVService__pb2.PaxosPhase1Req.FromString,
                    response_serializer=KVService__pb2.PaxosPhase1Resp.SerializeToString,
            ),
            'PaxosPhase2': grpc.unary_unary_rpc_method_handler(
                    servicer.PaxosPhase2,
                    request_deserializer=KVService__pb2.PaxosPhase2Req.FromString,
                    response_serializer=KVService__pb2.PaxosPhase2Resp.SerializeToString,
            ),
            'CommitKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitKey,
                    request_deserializer=KVService__pb2.CommitReq.FromString,
                    response_serializer=KVService__pb2.CommitResp.SerializeToString,
            ),
            'GetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValue,
                    request_deserializer=KVService__pb2.GetValueReq.FromString,
                    response_serializer=KVService__pb2.GetValueResp.SerializeToString,
            ),
            'GetItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItems,
                    request_deserializer=KVService__pb2.GetItemsReq.FromString,
                    response_serializer=KVService__pb2.GetItemsResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.proto.KVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommitedVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/CommitedVersion',
            KVService__pb2.CommitedVersionReq.SerializeToString,
            KVService__pb2.CommitedVersionResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaxosPhase1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/PaxosPhase1',
            KVService__pb2.PaxosPhase1Req.SerializeToString,
            KVService__pb2.PaxosPhase1Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PaxosPhase2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/PaxosPhase2',
            KVService__pb2.PaxosPhase2Req.SerializeToString,
            KVService__pb2.PaxosPhase2Resp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommitKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/CommitKey',
            KVService__pb2.CommitReq.SerializeToString,
            KVService__pb2.CommitResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/GetValue',
            KVService__pb2.GetValueReq.SerializeToString,
            KVService__pb2.GetValueResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/src.proto.KVService/GetItems',
            KVService__pb2.GetItemsReq.SerializeToString,
            KVService__pb2.GetItemsResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
